# Generated by Django 4.2.27 on 2026-02-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_end_date_budget_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Allowance', 'Allowance'), ('Overtime', 'Overtime'), ('Investment', 'Investment'), ('Other', 'Other')], max_length=50),
        ),
    ]
