# Generated by Django 4.2.27 on 2026-02-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_end_date_budget_start_date'),
        ('finance', '0005_expense_payment_method_alter_budget_category_and_more'),
    ]

    operations = [
    ]
