# Generated by Django 4.2.27 on 2026-02-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autosavings', to='finance.income'),
        ),
        migrations.AddField(
            model_name='savings',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
