# Generated by Django 6.0 on 2026-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expense_payment_method_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
