# Generated by Django 6.0 on 2026-02-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_reminder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Savings', 'Savings')], default='Income', max_length=10),
        ),
    ]
